// 台账初始演示数据：覆盖高风险待督导、连续低风险降级、结案冻结更正、重开一致性冲突四类场景

import { CaseRecord, Ledger, SafetyPlan } from "./types";

const safetyPlan: SafetyPlan = {
  warningSigns: "连续失眠、反复出现“活着没意义”念头、回避所有社交。",
  copingSteps: "立即停止饮酒；按清单做 10 分钟 grounding；每 2 小时向家属报备状态。",
  supporters: "同住姐姐（24 小时可联系）；同事 A（工作日白天）。",
  professionalContacts: "本市心理援助热线 400-161-9995；值班急诊：市精卫中心。",
  environmentSafety: "家中药物由姐姐上锁保管，移除阳台可攀爬物品，不独处过夜。",
};

export const seedLedger: Ledger = {
  cases: [
    {
      // 高风险：最近会谈待督导确认 —— 下一次会谈不能落盘
      id: "C-101",
      registeredAt: "2026-08-01",
      clientCode: "L-042",
      counselor: "王旻",
      topic: "抑郁伴自伤念头",
      status: "active",
      sessions: [
        {
          id: "s-101-1",
          date: "2026-08-01",
          riskLevel: "high",
          goal: "稳定即时危机，建立安全契约",
          summary: "近两周有自伤念头但无具体计划；情绪极度低落。已建立安全计划。",
          safetyPlan,
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 陈静",
          confirmedAt: "2026-08-03",
          isIntake: true,
        },
        {
          id: "s-101-2",
          date: "2026-08-15",
          riskLevel: "high",
          goal: "巩固安全计划执行，重建昼夜节律",
          summary: "念头频率下降，安全计划执行良好；仍有失眠。",
          safetyPlan,
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 陈静",
          confirmedAt: "2026-08-17",
        },
        {
          id: "s-101-3",
          date: "2026-09-05",
          riskLevel: "high",
          goal: "评估药物就诊依从性，维持危机监控",
          summary: "已就诊服药，但本周出现一次饮酒后念头反复；家属已加强看护。",
          safetyPlan,
          persisted: true,
          confirm: "pending",
        },
      ],
      corrections: [],
    },
    {
      // 中风险 → 连续两次低风险 → 降级生效（含判断依据）
      id: "C-204",
      registeredAt: "2026-07-10",
      clientCode: "L-119",
      counselor: "赵一帆",
      topic: "亲密关系冲突 / 焦虑",
      status: "active",
      sessions: [
        {
          id: "s-204-1",
          date: "2026-07-10",
          riskLevel: "medium",
          goal: "稳定情绪，识别沟通回避模式",
          summary: "因伴侣争吵引发惊恐发作两次，社会功能尚可。",
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 林岚",
          confirmedAt: "2026-07-12",
          isIntake: true,
        },
        {
          id: "s-204-2",
          date: "2026-07-24",
          riskLevel: "low",
          goal: "练习非暴力沟通，观察情绪波动",
          summary: "两周无惊恐发作，能主动表达需求；为首次低风险，进入观察期。",
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 林岚",
          confirmedAt: "2026-07-26",
        },
        {
          id: "s-204-3",
          date: "2026-08-07",
          riskLevel: "low",
          goal: "巩固边界练习，逐步延长会谈间隔",
          summary: "连续四周无惊恐，工作与社交恢复，冲突中可使用暂停与复述技巧。",
          downgradeBasis:
            "依据：连续两次会谈（07-24、08-07）评定低风险；期间无自伤/惊恐，社会功能恢复，支持者反馈稳定，PHQ-9 由 14 降至 6。",
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 林岚",
          confirmedAt: "2026-08-09",
        },
      ],
      corrections: [],
    },
    {
      // 已结案冻结：后续修改只能以更正形式留痕
      id: "C-317",
      registeredAt: "2026-05-02",
      clientCode: "L-203",
      counselor: "王旻",
      topic: "职业压力 / 适应障碍",
      status: "closed",
      closedAt: "2026-08-20",
      sessions: [
        {
          id: "s-317-1",
          date: "2026-05-02",
          riskLevel: "low",
          goal: "评估压力源，制定边界练习计划",
          summary: "职业倦怠、入睡困难，无危机因素。",
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 陈静",
          confirmedAt: "2026-05-04",
          isIntake: true,
        },
        {
          id: "s-317-2",
          date: "2026-08-18",
          riskLevel: "low",
          goal: "结案评估，巩固自我照顾计划",
          summary: "睡眠恢复，已完成调岗，自评压力可控。",
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 陈静",
          confirmedAt: "2026-08-19",
        },
      ],
      corrections: [
        {
          id: "cor-317-1",
          targetType: "session",
          targetId: "s-317-2",
          field: "summary",
          original: "睡眠恢复，已完成调岗，自评压力可控。",
          corrected: "睡眠恢复，已完成岗位调整协商（非调岗），自评压力可控。",
          reason: "来访者来电澄清，原记录将“岗位调整协商”误写为“完成调岗”，属事实性错误。",
          responsible: "王旻（咨询师）/ 陈静（督导核准）",
          createdAt: "2026-08-25",
        },
      ],
    },
    {
      // 已重开：会谈落盘/确认链路存在不一致，供一致性核对演示
      id: "C-451",
      registeredAt: "2026-03-14",
      clientCode: "L-308",
      counselor: "赵一帆",
      topic: "亲子冲突 / 情绪失调",
      status: "reopened",
      closedAt: "2026-07-30",
      reopenedAt: "2026-09-02",
      reopenReason: "开学后亲子冲突升级，来访者主动求助，危机信号复现。",
      sessions: [
        {
          id: "s-451-1",
          date: "2026-03-14",
          riskLevel: "low",
          goal: "建立联盟，评估家庭互动模式",
          summary: "亲子争吵频繁，孩子情绪激动但无伤害风险。",
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 林岚",
          confirmedAt: "2026-03-16",
          isIntake: true,
        },
        {
          id: "s-451-2",
          date: "2026-07-25",
          riskLevel: "low",
          goal: "结案评估",
          summary: "冲突频率显著下降，家庭规则建立。",
          persisted: true,
          confirm: "confirmed",
          confirmedBy: "督导 林岚",
          confirmedAt: "2026-07-27",
        },
        {
          // 重开后首次会谈：中风险，尚未督导确认，且未落盘
          id: "s-451-3",
          date: "2026-09-03",
          riskLevel: "medium",
          goal: "重新评估风险，恢复应对练习",
          summary: "摔门、拒学两次，无自伤伤人计划；已约定家长看护。",
          persisted: false,
          confirm: "pending",
        },
        {
          // 不一致点：上一次会谈尚未确认，本次却已落盘
          id: "s-451-4",
          date: "2026-09-17",
          riskLevel: "medium",
          goal: "家校沟通协调",
          summary: "已复课三天；家校建立每日反馈。注：本次在上一次会谈未获督导确认前被落盘。",
          persisted: true,
          confirm: "pending",
        },
      ],
      corrections: [],
    },
  ] as CaseRecord[],
};
