// 种子数据：覆盖各规则的典型场景
// C-1024 高风险 + 安全计划 + 最近一次高风险会谈待督导确认（演示 R2 拦截）
// C-2031 中风险 + 仅一次低风险评估（演示 R3 降级拦截 → 补一次低风险会谈后可降级）
// C-3099 低风险已结案 + 一条更正记录（演示 R4 冻结、R5 更正留痕、重开一致性）

import { LedgerState } from "./types";

export const seedState: LedgerState = {
  seq: 2000,
  cases: [
    {
      id: "C-1024",
      clientAlias: "来访者-A17",
      counselor: "周咨询",
      registeredAt: "2026-08-30",
      riskLevel: "high",
      goals: ["降低自伤意念频率", "建立情绪危机应对清单"],
      safetyPlan: {
        warningSigns: "连续失眠、反复表达“撑不下去”",
        copingStrategies: "腹式呼吸、着陆练习、联系支持名单",
        emergencyContacts: "姐姐 138****2210；危机热线 400-161-9995",
        meansRestriction: "药物交由家属保管，移除尖锐物品",
        createdBy: "周咨询",
        createdAt: "2026-08-30",
      },
      status: "active",
      closedAt: null,
      closeReason: null,
      reopenHistory: [],
      riskLog: [
        {
          date: "2026-09-12",
          from: "medium",
          to: "high",
          reason: "会谈评估上调：出现被动自伤意念，有具体场景想象",
          by: "周咨询",
        },
      ],
      sessions: [
        {
          id: "S-1001",
          caseId: "C-1024",
          date: "2026-09-05",
          riskLevel: "medium",
          rationale: "情绪低谷但无自伤意念，社会支持尚可",
          summary: "探讨工作压力源，建立情绪记录表",
          nextGoal: "完成一周情绪记录",
          counselor: "周咨询",
          confirmation: null,
        },
        {
          id: "S-1002",
          caseId: "C-1024",
          date: "2026-09-12",
          riskLevel: "high",
          rationale: "出现被动自伤意念，有具体场景想象，保护性因素尚存",
          summary: "危机评估，现场启动安全计划并与家属通气",
          nextGoal: "每日安全打卡，24 小时随访",
          counselor: "周咨询",
          confirmation: null,
        },
      ],
      corrections: [],
    },
    {
      id: "C-2031",
      clientAlias: "来访者-B04",
      counselor: "吴咨询",
      registeredAt: "2026-08-18",
      riskLevel: "medium",
      goals: ["识别沟通中的回避模式", "练习直接表达需求"],
      safetyPlan: null,
      status: "active",
      closedAt: null,
      closeReason: null,
      reopenHistory: [],
      riskLog: [],
      sessions: [
        {
          id: "S-1003",
          caseId: "C-2031",
          date: "2026-09-01",
          riskLevel: "medium",
          rationale: "伴侣冲突仍激烈，情绪调节吃力但无风险信号",
          summary: "梳理最近一次冲突的触发点",
          nextGoal: "记录一次冲突中的自动化想法",
          counselor: "吴咨询",
          confirmation: null,
        },
        {
          id: "S-1004",
          caseId: "C-2031",
          date: "2026-09-15",
          riskLevel: "low",
          rationale: "连续两周情绪平稳，冲突可自我调节，睡眠恢复正常",
          summary: "回顾沟通练习成效，回避模式明显松动",
          nextGoal: "维持练习，观察一周",
          counselor: "吴咨询",
          confirmation: null,
        },
      ],
      corrections: [],
    },
    {
      id: "C-3099",
      clientAlias: "来访者-C22",
      counselor: "周咨询",
      registeredAt: "2026-07-20",
      riskLevel: "low",
      goals: ["设定下周边界练习"],
      safetyPlan: null,
      status: "closed",
      closedAt: "2026-09-10",
      closeReason: "目标达成，双方同意结案（结案人：周咨询）",
      reopenHistory: [],
      riskLog: [],
      sessions: [
        {
          id: "S-1005",
          caseId: "C-3099",
          date: "2026-08-28",
          riskLevel: "low",
          rationale: "状态稳定，边界练习执行良好",
          summary: "边界练习回顾；补充：家属共同参与后半段",
          nextGoal: "维持现有节奏，必要时预约随访",
          counselor: "周咨询",
          confirmation: null,
        },
      ],
      corrections: [
        {
          id: "COR-1001",
          targetType: "session",
          targetId: "S-1005",
          field: "summary",
          fieldLabel: "会谈摘要",
          originalContent: "边界练习回顾",
          newContent: "边界练习回顾；补充：家属共同参与后半段",
          reason: "原记录遗漏共同在场人员信息",
          responsible: "周咨询",
          correctedAt: "2026-09-11",
        },
      ],
    },
  ],
};
